apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: ghcr.io/vishnumuthyalu/waypoint-analytics
  newName: ghcr.io/vishnumuthyalu/waypoint-analytics
  newTag: 697de4aa37858c80ac735ee7c79ed76cac109eed
- name: ghcr.io/vishnumuthyalu/waypoint-bff
  newName: ghcr.io/vishnumuthyalu/waypoint-bff
  newTag: 697de4aa37858c80ac735ee7c79ed76cac109eed
- name: ghcr.io/vishnumuthyalu/waypoint-links
  newName: ghcr.io/vishnumuthyalu/waypoint-links
  newTag: 697de4aa37858c80ac735ee7c79ed76cac109eed
- name: ghcr.io/vishnumuthyalu/waypoint-redirect
  newName: ghcr.io/vishnumuthyalu/waypoint-redirect
  newTag: 697de4aa37858c80ac735ee7c79ed76cac109eed
